import { StyleSheet } from "react-native";
import { ThemeColors } from "../../types";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    backdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.6)",
      justifyContent: "flex-end",
    },
    modalContainer: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: "85%",
      overflow: "hidden",
    },
    header: {
      position: "relative",
      paddingTop: 12,
      paddingHorizontal: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
      zIndex: 10,
    },
    dragIndicator: {
      width: 40,
      height: 4,
      backgroundColor: colors.border,
      borderRadius: 2,
      alignSelf: "center",
      marginBottom: 12,
    },
    closeButton: {
      position: "absolute",
      top: 12,
      right: 20,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.background,
      justifyContent: "center",
      alignItems: "center",
      elevation: 4,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    closeButtonPressed: {
      opacity: 0.7,
      transform: [{ scale: 0.95 }],
    },
    scrollContent: {
      paddingBottom: 120,
    },
    imageContainer: {
      width: "100%",
      height: 280,
      position: "relative",
      backgroundColor: colors.background,
    },
    image: {
      width: "100%",
      height: "100%",
    },
    imagePlaceholder: {
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },
    categoryBadge: {
      position: "absolute",
      top: 16,
      left: 16,
      backgroundColor: colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 12,
      elevation: 3,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    categoryText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "700",
    },
    content: {
      padding: 20,
    },
    nameSection: {
      marginBottom: 16,
    },
    name: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 8,
      lineHeight: 32,
    },
    ratingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    ratingContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      backgroundColor: colors.background,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
    },
    ratingText: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
    },
    reviewCount: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    priceSection: {
      backgroundColor: colors.background,
      padding: 16,
      borderRadius: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    priceLabel: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    price: {
      fontSize: 32,
      fontWeight: "bold",
      color: colors.shadow,
    },
    descriptionSection: {
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 8,
    },
    description: {
      fontSize: 15,
      color: colors.textSecondary,
      lineHeight: 24,
    },
    featuresSection: {
      marginBottom: 20,
    },
    featureItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 12,
      backgroundColor: colors.background,
      padding: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    featureIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.primaryDark,
      justifyContent: "center",
      alignItems: "center",
    },
    featureText: {
      fontSize: 14,
      color: colors.shadow,
      flex: 1,
      fontWeight: "500",
    },
    footer: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.card,
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      elevation: 8,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    footerContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    priceInfo: {
      flex: 1,
    },
    footerPriceLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    footerPrice: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.primary,
    },
    cartControls: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    quantityContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 6,
      paddingVertical: 6,
      gap: 10,
    },
    quantityButton: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    quantityButtonDisabled: {
      backgroundColor: colors.border,
      opacity: 0.5,
    },
    quantityButtonPressed: {
      opacity: 0.7,
      transform: [{ scale: 0.9 }],
    },
    quantityText: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.text,
      minWidth: 28,
      textAlign: "center",
    },
    doneButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.success,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
      gap: 6,
      elevation: 4,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    doneButtonPressed: {
      opacity: 0.8,
      transform: [{ scale: 0.98 }],
    },
    doneButtonText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "bold",
    },
    addButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.success,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
      gap: 6,
      elevation: 4,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    addButtonPressed: {
      opacity: 0.8,
      transform: [{ scale: 0.98 }],
    },
    addButtonText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "bold",
    },
  });